# Generated by Django 2.1.2 on 2019-03-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCreditOrder',
            fields=[
                ('add_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'add_credit_order',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'borrow',
            },
        ),
        migrations.CreateModel(
            name='BorrowOrder',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('supposedate', models.DateTimeField(blank=True, null=True)),
                ('actdate', models.DateTimeField(blank=True, null=True)),
                ('penatly_status', models.CharField(blank=True, max_length=255, null=True)),
                ('appeal_status', models.CharField(blank=True, max_length=255, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Borrow')),
            ],
            options={
                'db_table': 'borrow_order',
            },
        ),
        migrations.CreateModel(
            name='BorrowRule',
            fields=[
                ('education', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'borrow_rule',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certi_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='CultivatePlan',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('major_id', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cultivate_plan',
            },
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('dorm_id', models.IntegerField()),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dorm',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='LostHistory',
            fields=[
                ('lost_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.BorrowOrder')),
            ],
            options={
                'db_table': 'lost_history',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_comm', models.IntegerField(blank=True, null=True)),
                ('buyer_comm', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('stu_pen_id', models.AutoField(primary_key=True, serialize=False)),
                ('pen_money', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'penalty',
            },
        ),
        migrations.CreateModel(
            name='PenAppeal',
            fields=[
                ('pen_appeal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('stu_pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Penalty')),
            ],
            options={
                'db_table': 'pen_appeal',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_org', models.IntegerField(blank=True, null=True)),
                ('price_cur', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='RoommateComment',
            fields=[
                ('comm_id', models.AutoField(primary_key=True, serialize=False)),
                ('dorm_id', models.IntegerField(blank=True, null=True)),
                ('comm_maker_id', models.IntegerField(blank=True, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roommate_comment',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('stu_comm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'scholarship',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_pwd', models.CharField(blank=True, max_length=255, null=True)),
                ('stu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stu_year', models.TextField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('bed_id', models.IntegerField(blank=True, null=True)),
                ('dorm_id', models.IntegerField(blank=True, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Instructor')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Major')),
                ('stu_edu', models.ForeignKey(blank=True, db_column='stu_edu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.BorrowRule')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentChoice',
            fields=[
                ('student_choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('stu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Student')),
            ],
            options={
                'db_table': 'student_choice',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tea_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Major')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherChoice',
            fields=[
                ('teacher_choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_year', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('classroom', models.ForeignKey(blank=True, db_column='classroom', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.CultivatePlan')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Teacher')),
            ],
            options={
                'db_table': 'teacher_choice',
            },
        ),
        migrations.AddField(
            model_name='studentchoice',
            name='teacher_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.TeacherChoice'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.StudentChoice'),
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Student'),
        ),
        migrations.AddField(
            model_name='penappeal',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Teacher'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='borrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Student'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='education',
            field=models.ForeignKey(blank=True, db_column='education', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.BorrowRule'),
        ),
        migrations.AddField(
            model_name='orders',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Student'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Products'),
        ),
        migrations.AlterUniqueTogether(
            name='dorm',
            unique_together={('bed_id', 'dorm_id')},
        ),
        migrations.AddField(
            model_name='credit',
            name='stu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Student'),
        ),
        migrations.AddField(
            model_name='certification',
            name='student_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.StudentChoice'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='stu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Student'),
        ),
        migrations.AddField(
            model_name='addcreditorder',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Rules'),
        ),
        migrations.AddField(
            model_name='addcreditorder',
            name='stu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mybishe.Student'),
        ),
    ]
